version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      time: '07:00'
    open-pull-requests-limit: 10
    allow:
      - dependency-type: all
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: all