services:
  monitoring:
    build: .
    container_name: monitoring
    ports: 
      - $PORT:$PORT
    environment:
      - SEND_ADDRESS
      - SEND_PASSWORD
      - SMTP_RELAY
      - TO_ADDRESS
      - PORT
    image: lucas42/lucos_monitoring
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${PORT}/_info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    network_mode: host
