version: 2.1

jobs:
  test:
    docker:
      - image: cimg/elixir
    steps:
      - checkout
      - run:
          name: Run Tests
          command: rebar3 do eunit --cover, cover
      - store_artifacts:
          path: _build/test/cover

orbs:
  lucos: lucos/deploy@0
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - lucos/build-amd64
      - lucos/deploy-avalon:
          requires:
            - test
            - lucos/build-amd64
          filters:
            branches:
              only:
                - main