name: Convention check

on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  convention-check:
    uses: lucas42/.github/.github/workflows/convention-check.yml@51ddef78f3356ca91b93d1e59da01c4d2f32c08e
