name: Convention check

on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  convention-check:
    uses: lucas42/.github/.github/workflows/reusable-convention-check.yml@v1.18.0
